Repository inspirehep/inspire-next, pull requests merged in 2018-03, with the labels that each got.

#3227 Revert "workflows: add hp card for all publisher harvests"
  inspirehep/modules/workflows/templates/inspire_workflows/index.html
Labels: Review: WIP

#3233 orcid: add a feature flag for ORCID push
  inspirehep/config.py
  inspirehep/modules/records/receivers.py
  tests/integration/records/test_records_receivers.py
Labels: Review: WIP

#3218 orcid: override oauth setup signup handler
  inspirehep/config.py
  inspirehep/modules/orcid/utils.py
Labels: Review: Ready for Integration

#3224 utils: add get_db_records util
  inspirehep/utils/record_getter.py
  tests/integration/test_records.py
  tests/integration/utils/test_record_getter.py
Labels: Review: Ready for Integration

#3223 orcid: also push to orcid in author record
  inspirehep/modules/orcid/utils.py
  inspirehep/modules/records/receivers.py
  setup.py
  tests/integration/orcid/test_orcid_utils.py
Labels: Review: Ready for Integration

#3234 setup: bump ``invenio-indexer`` version
  requirements.txt
  setup.py
Labels: Review: WIP

#3232 orcid.builder: order contributor fields correctly
  inspirehep/modules/orcid/builder.py
  tests/integration/orcid/test_orcid_export.py
  tests/unit/orcid/test_orcid_builder.py
Labels: Review: WIP

#3236 forms: fix orcid validation after API update
  inspirehep/modules/forms/validation_utils.py
  tests/unit/forms/test_forms_validation_utils.py
Labels: Review: WIP

#3235 orcid-sync: remove Redis Lock
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/test_orcid_import_legacy_tokens.py
Labels: Review: WIP

#3237 orcid-sync: force allow_push on tokens in Labs INSPIR-44
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/test_orcid_import_legacy_tokens.py
Labels: Review: Ready for Review

#3238 forms: add, populate and validate ORCID field
  inspirehep/modules/authors/forms.py
Labels: Review: Ready for Review, Type: Feature

#3240 workflows: get first five recid when fuzzy match
  inspirehep/modules/workflows/tasks/matching.py
  tests/integration/workflows/test_arxiv_workflow.py
Labels: Review: In Review

#3231 setup: pin new versions of inspire-crawler and hepcrawl
  setup.py
Labels: Review: Ready for Integration

#3241 Orcidsync
  inspirehep/modules/orcid/tasks.py
Labels: Review: WIP

#3244 orcid-sync: add whitelist INSPIR-44
  inspirehep/config.py
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/test_orcid_push.py
Labels: Review: WIP

#3247 setup: add explicitly the pyOpenSSL dependency
  setup.py
Labels: Review: WIP

#3245 setup: unpin SQLAlchemy
  setup.py
Labels: Review: Ready for Review

#3249 orcid: fix ORCID login INSPIR-243
  inspirehep/modules/orcid/utils.py
Labels: Review: WIP

#3250 holdingpen: add crawl_errors to search results
  inspirehep/modules/workflows/search.py
Labels: Review: Ready for Review

#3246 migrator.tasks: disable migration on ORCID push
  inspirehep/modules/migrator/tasks.py
  inspirehep/modules/orcid/tasks.py
  tests/integration/migrator/fixtures/dummy.xml
  tests/integration/migrator/test_migrator_tasks.py
Labels: Review: WIP

#3194 arxiv: decode latex charachters in authors' full_name
  inspirehep/modules/workflows/tasks/arxiv.py
  inspirehep/utils/latex.py
  setup.py
  tests/unit/utils/test_utils_latex.py
  tests/unit/workflows/fixtures/1802.03388.tar.gz
  tests/unit/workflows/test_workflows_tasks_arxiv.py
Labels: Review: In Review

#3251 matching: add feature flag for the fuzzy matcher
  inspirehep/config.py
  inspirehep/modules/workflows/tasks/matching.py
  tests/integration/workflows/test_arxiv_workflow.py
  tests/unit/workflows/test_workflows_tasks_matching.py
Labels: Review: WIP

#3253 receivers: tests fix: migration orcid push disable
  tests/integration/migrator/test_migrator_tasks.py
Labels: Review: WIP

#3254 records: don't push to ORCiD without recid
  inspirehep/modules/records/receivers.py
  tests/integration/workflows/test_workflows_tasks_upload.py
Labels: Review: WIP

#3255 gitignore: add .pytest_cache
  .gitignore
Labels: Review: WIP

#3239 workflows: add validation errors callback
  inspirehep/modules/workflows/errors.py
  inspirehep/modules/workflows/loaders.py
  inspirehep/modules/workflows/search.py
  inspirehep/modules/workflows/serializers/__init__.py
  inspirehep/modules/workflows/serializers/schemas/__init__.py
  inspirehep/modules/workflows/serializers/schemas/json.py
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/utils/__init__.py
  inspirehep/modules/workflows/views.py
  tests/integration/workflows/helpers/calls.py
  tests/integration/workflows/test_arxiv_workflow.py
Labels: Review: In Review

#3256 holdingpen: fix publisher harverst card query
  inspirehep/modules/workflows/templates/inspire_workflows/index.html
Labels: Review: Ready for Review

#3260 workflows: fix and refactor is_experimental_paper
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/utils/record.py
  tests/unit/utils/test_utils_record.py
  tests/unit/workflows/test_workflows_tasks_actions.py
Labels: Review: WIP

#3261 workflows: do the automatic decision before halt
  inspirehep/modules/workflows/workflows/article.py
Labels: Review: WIP

#3263 Hotfix 2018-03-16
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/workflows/article.py
  inspirehep/utils/record.py
  tests/unit/utils/test_utils_record.py
  tests/unit/workflows/test_workflows_tasks_actions.py
Labels: Review: WIP

#3258 workflow fix for preventing rejecting reharvests
  inspirehep/modules/workflows/workflows/article.py
  tests/integration/workflows/test_arxiv_workflow.py
Labels: Review: WIP

#3268 workflow: retry arxiv download from non-export url INSPIR-237
  inspirehep/config.py
  inspirehep/modules/workflows/tasks/arxiv.py
  tests/unit/workflows/test_workflows_tasks_arxiv.py
Labels: Review: WIP

#3274 workflows: move stopping of duplicate submission in appropriate step
  inspirehep/modules/workflows/workflows/article.py
Labels: Review: WIP

#3269 orcid: store record hashes to not send redundant updates
  inspirehep/modules/orcid/api.py
  inspirehep/modules/orcid/tasks.py
  inspirehep/modules/orcid/utils.py
  setup.py
  tests/integration/orcid/cassettes/test_get_author_putcodes.yaml
  tests/integration/orcid/cassettes/test_push_record_with_orcid_dont_push_if_no_change.yaml
  tests/integration/orcid/cassettes/test_push_record_with_orcid_new.yaml
  tests/integration/orcid/cassettes/test_push_record_with_orcid_update.yaml
  tests/integration/orcid/cassettes/test_push_to_orcid_same_with_cache.yaml
  tests/integration/orcid/cassettes/test_push_to_orcid_update_no_cache.yaml
  tests/integration/orcid/cassettes/test_push_to_orcid_update_with_cache.yaml
  tests/integration/orcid/cassettes/test_push_to_orcid_with_putcode_but_without_hash.yaml
  tests/integration/orcid/conftest.py
  tests/integration/orcid/fixtures/casette_push_no_cache.yaml
  tests/integration/orcid/fixtures/casette_push_with_cache.yaml
  tests/integration/orcid/test_orcid_api.py
  tests/integration/orcid/test_orcid_export.py
  tests/integration/orcid/test_orcid_push.py
  tests/unit/orcid/test_orcid_utils.py
Labels: Review: WIP

#3282 setup: put pytest-vcr in the right place
  setup.py
Labels: Review: WIP

#3265 tests: make the unit tests run without internet
  tests/unit/workflows/fixtures/1605.07707
  tests/unit/workflows/fixtures/1612.00624
  tests/unit/workflows/fixtures/1612.00626
  tests/unit/workflows/test_workflows_tasks_actions.py
  tests/unit/workflows/test_workflows_tasks_arxiv.py
Labels: Review: WIP

#3289 setup: pin Celery
  setup.py
Labels: Review: WIP

#3279 orcid: add get_literature_recids_by_orcid util
  inspirehep/modules/authors/rest/citations.py
  inspirehep/modules/authors/rest/coauthors.py
  inspirehep/modules/authors/rest/publications.py
  inspirehep/modules/authors/rest/stats.py
  inspirehep/modules/orcid/utils.py
  inspirehep/modules/records/mappings/records/hep.json
  tests/integration/conftest.py
  tests/integration/orcid/test_orcid_utils.py
  tests/integration/test_db_isolation.py
Labels: Review: WIP

#3278 mappings: add mappings for data
  inspirehep/modules/records/mappings/records/data.json
Labels: Review: WIP

#3280 workflows: add more data for fuzzy match results
  inspirehep/config.py
  inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
  inspirehep/modules/workflows/tasks/matching.py
  tests/integration/workflows/test_arxiv_workflow.py
  tests/unit/workflows/test_workflows_tasks_matching.py
Labels: Review: WIP

#3287 workflow: snippet script to delete records without control_number INS…
  scripts/delete_records.py
Labels: Review: WIP

#3277 Change fuzzy matcher config to use Jaccard Index based validator
  inspirehep/config.py
Labels: Review: Ready for Review, Review: WIP

#3286 Two step migration
  inspirehep/config.py
  inspirehep/modules/fixtures/cli.py
  inspirehep/modules/migrator/cli.py
  inspirehep/modules/migrator/ext.py
  inspirehep/modules/migrator/models.py
  inspirehep/modules/migrator/tasks.py
  inspirehep/utils/schema.py
  tests/acceptance/conftest.py
  tests/integration/conftest.py
  tests/integration/migrator/fixtures/1663923.xml
  tests/integration/migrator/fixtures/1663924.xml
  tests/integration/migrator/fixtures/1663927_broken.xml
  tests/integration/migrator/test_migrator_cli.py
  tests/integration/migrator/test_migrator_models.py
  tests/integration/migrator/test_migrator_tasks.py
  tests/unit/migrator/fixtures/1663923.xml
  tests/unit/migrator/fixtures/1663924.xml
  tests/unit/migrator/fixtures/1663924.xml.gz
  tests/unit/migrator/fixtures/micro-prodsync.tar
  tests/unit/migrator/test_migrator_tasks.py
Labels: Review: WIP

#3294 workflows: make fuzzy match ui more compact
  inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
Labels: Review: WIP

#3297 records: correctly skip files in create_or_update
  inspirehep/modules/records/api.py
Labels: Review: WIP

#3295 add clear button to authorlist page
  inspirehep/modules/tools/templates/authorlist_form.html
Labels: Review: WIP

#3300 setup: pin invenio-oauthclient INSPIR-434
  setup.py
Labels: Review: WIP

#3303 db: sql snippet to create index on RecordMetadata.json INSPIR-375
  scripts/index_on_jsonb_field.txt
Labels: Review: WIP

#3298 orcid: plug get_literature_recids_for_orcid
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/test_orcid_import_legacy_tokens.py
Labels: Review: WIP

#3304 setup: remove pin on invenio-oauthclient
  setup.py
Labels: Review: WIP

#3306 scripts: use migrate, not migrator
  INSTALL.rst
  inspirehep/modules/migrator/cli.py
  scripts/recreate_records
Labels: Review: WIP

#3302 setup: unpin Celery
  setup.py
Labels: Review: WIP
