Repository inspirehep/inspire-next, pull requests merged in 2018-06, with the labels that each got.

#3438 docker-compose.yml: don't proxy
  docker-compose.yml
Labels: Review: WIP

#3439 e2e: add external system calls assertions
  tests/e2e/test_arxiv_harvest.py
Labels: Review: WIP

#3437 config: consolidate usage of dicts and rest endpoints
  inspirehep/config.py
Labels: Review: WIP

#3442 831 requirements: pin SQLAlchemy-Continuum==1.3.4
  setup.py
Labels: Review: WIP

#3441 disambiguation: add ethnicity estimator
  inspirehep/modules/disambiguation/core/ml/__init__.py
  inspirehep/modules/disambiguation/core/ml/models.py
  setup.py
  tests/unit/disambiguation/test_disambiguation_core_ml_models.py
Labels: Review: WIP

#3447 841 requirements: pin urllib3==1.22
  setup.py
Labels: Review: WIP

#3445 759 e2e: add manual accept core harvest test
  inspirehep/testlib/api/holdingpen.py
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/ArxivService/core_article.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/ArxivService/eprint_tarball.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/ArxivService/fulltext_pdf.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/LegacyService/allocaterecord.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/LegacyService/robotupload.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/RTService/authenticate.yaml
  tests/e2e/scenarios/harvest_core_article_manual_accept_goes_in/RTService/ticket_new.yaml
  tests/e2e/test_arxiv_harvest.py
Labels: Review: Ready for Review

#3450 842 holdingpen: publisher workflows box and is-update not set
  inspirehep/modules/workflows/templates/inspire_workflows/index.html
Labels: Review: WIP

#3417 migrator: REST-ful API for Legacy Mirror
  inspirehep/alembic/eaab22c59b89_insert_migrator_use_api_action_role.py
  inspirehep/alembic/f9ea5752e7a5_update_legacy_records_mirror_table.py
  inspirehep/modules/fixtures/users.py
  inspirehep/modules/migrator/cli.py
  inspirehep/modules/migrator/dumper.py
  inspirehep/modules/migrator/models.py
  inspirehep/modules/migrator/permissions.py
  inspirehep/modules/migrator/serializers/__init__.py
  inspirehep/modules/migrator/serializers/schemas/__init__.py
  inspirehep/modules/migrator/serializers/schemas/json.py
  inspirehep/modules/migrator/utils.py
  inspirehep/modules/migrator/views.py
  setup.py
  tests/integration/conftest.py
  tests/integration/helpers/factories/db/inspire_migrator.py
  tests/integration/migrator/fixtures/1674987.xml
  tests/integration/migrator/fixtures/1674989.xml
  tests/integration/migrator/fixtures/1674997.xml
  tests/integration/migrator/test_migrator_models.py
  tests/integration/migrator/test_migrator_view.py
Labels: Review: WIP

#3452 disambiguation: fix typo in configuration key
  inspirehep/modules/disambiguation/ext.py
Labels: Review: WIP

#3453 disambiguation: add get_all_signatures
  inspirehep/modules/disambiguation/core/db/readers.py
  tests/integration/disambiguation/test_disambiguation_core_db_readers.py
Labels: Review: WIP

#3457 records: don't assign an empty signature_block
  inspirehep/modules/records/receivers.py
  tests/unit/records/test_records_receivers.py
Labels: Review: WIP

#3454 disambiguation: refactor to use JSON Lines
  inspirehep/modules/disambiguation/api.py
  inspirehep/modules/disambiguation/ext.py
  tests/integration/disambiguation/test_disambiguation_api.py
Labels: Review: WIP

#3459 792 testlib: add mitmproxy scenario recording client
  inspirehep/testlib/api/mitm_client.py
  tests/e2e/test_arxiv_harvest.py
Labels: Review: WIP

#3444 records: add functionality check unlinked references
  inspirehep/modules/records/checkers.py
  inspirehep/modules/records/cli.py
  inspirehep/modules/records/ext.py
  setup.py
  tests/integration/records/test_cli.py
Labels: Review: WIP

#3460 disambiguation: add signature pairs sampling
  inspirehep/modules/disambiguation/api.py
  inspirehep/modules/disambiguation/config.py
  inspirehep/modules/disambiguation/core/ml/sampling.py
  inspirehep/modules/disambiguation/ext.py
  tests/integration/disambiguation/fixtures/765515.json
  tests/integration/disambiguation/fixtures/765975.json
  tests/integration/disambiguation/test_disambiguation_api.py
Labels: Review: WIP

#3464 workflows: addition of copy local files
  inspirehep/modules/records/api.py
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/utils/__init__.py
  tests/integration/records/test_records_api.py
  tests/unit/workflows/test_workflows_tasks_actions.py
  tests/unit/workflows/test_workflows_utils.py
Labels: Review: WIP

#3462 workflows: don't ref-match hidden and deleted recs
  inspirehep/modules/workflows/config.py
  setup.py
  tests/integration/workflows/test_workflows_tasks_refextract.py
Labels: Review: WIP

#3466 v0.10.1
  inspirehep/modules/disambiguation/api.py
  inspirehep/modules/disambiguation/config.py
  inspirehep/modules/disambiguation/core/ml/sampling.py
  inspirehep/modules/disambiguation/ext.py
  inspirehep/modules/records/api.py
  inspirehep/modules/records/checkers.py
  inspirehep/modules/records/cli.py
  inspirehep/modules/records/ext.py
  inspirehep/modules/records/receivers.py
  inspirehep/modules/workflows/config.py
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/utils/__init__.py
  inspirehep/testlib/api/mitm_client.py
  setup.py
  tests/e2e/test_arxiv_harvest.py
  tests/integration/disambiguation/fixtures/765515.json
  tests/integration/disambiguation/fixtures/765975.json
  tests/integration/disambiguation/test_disambiguation_api.py
  tests/integration/records/test_cli.py
  tests/integration/records/test_records_api.py
  tests/integration/workflows/test_workflows_tasks_refextract.py
  tests/unit/records/test_records_receivers.py
  tests/unit/workflows/test_workflows_tasks_actions.py
  tests/unit/workflows/test_workflows_utils.py
Labels: Review: WIP

#3470 docs: add a tutorial on how to write E2E tests
  docs/e2e_tutorial.rst
  docs/index.rst
Labels: Review: WIP

#3458 migrator view: filter out 'DELETED' invalid records
  inspirehep/alembic/2f5368ff6d20_update_indices_on_legacy_records_mirror_table.py
  inspirehep/modules/migrator/models.py
  inspirehep/modules/migrator/views.py
  tests/integration/migrator/test_migrator_view.py
Labels: Review: WIP

#3467 records: link doi and arxiv eprint of unlinked literature
  inspirehep/modules/records/checkers.py
  tests/integration/records/test_cli.py
Labels: Review: WIP

#3499 workflows: increase refextract timeout to 10 min
  inspirehep/modules/workflows/tasks/actions.py
Labels: Review: WIP

#3465 records: fix transaction issue causing zomie pids
  inspirehep/modules/records/api.py
  tests/integration/records/test_records_api.py
Labels: Review: WIP

#3503 workflows: put the refextract timeout on subtasks
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/tasks/refextract.py
Labels: Review: WIP

#3497 907 workflows: make HP hep mapping non-dynamic
  docs/operations.rst
  inspirehep/modules/workflows/mappings/holdingpen/hep.json
Labels: Review: WIP

#3507 holdingpen: fix holdingpen-hep mapping for facets
  inspirehep/modules/workflows/mappings/holdingpen/hep.json
Labels: Review: WIP

#3511 workflows: no error when refextract times out
  inspirehep/modules/workflows/tasks/arxiv.py
  inspirehep/modules/workflows/tasks/refextract.py
  inspirehep/modules/workflows/utils/__init__.py
  tests/unit/workflows/test_workflows_utils.py
Labels: Review: Ready for Integration

#3512 v0.11.2
  inspirehep/modules/orcid/utils.py
  inspirehep/modules/records/serializers/schemas/json.py
  inspirehep/modules/records/utils.py
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/tasks/arxiv.py
  inspirehep/modules/workflows/tasks/refextract.py
  inspirehep/modules/workflows/utils/__init__.py
  inspirehep/modules/workflows/workflows/article.py
  inspirehep/utils/record_getter.py
  tests/integration/helpers/factories/db/invenio_records.py
  tests/integration/records/fixtures/1575134.json
  tests/integration/records/serializers/test_schemas_json.py
  tests/integration/records/test_records_utils.py
  tests/integration/utils/test_record_getter.py
  tests/integration/workflows/test_workflows_tasks_actions.py
  tests/unit/records/serializers/test_schemas_json.py
  tests/unit/workflows/test_workflows_utils.py
Labels: Review: WIP

#3515 edit_article: use always latest data from db as payload
  inspirehep/modules/workflows/workflows/edit_article.py
  tests/integration/workflows/test_edit_article.py
Labels: Review: Ready for Review

#3516 Revert "Automatic merge pull request #3515 from ammirate/edit_article…
  inspirehep/modules/workflows/workflows/edit_article.py
  tests/integration/workflows/test_edit_article.py
Labels: Review: WIP

#3416 scripts: add modify_record
  scripts/modify_record.py
Labels: Review: WIP

#3488 workflows: make reference information available to the templates
  inspirehep/modules/workflows/search.py
Labels: Review: WIP

#3522 e2e: fix small nits
  inspirehep/testlib/api/base_resource.py
  tests/e2e/test_arxiv_harvest.py
Labels: Review: WIP
