Repository inspirehep/inspire-next, pull requests merged in 2018-02, with the labels that each got.

#3184 workflows: improve reference handling
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/tasks/refextract.py
  inspirehep/modules/workflows/tasks/submission.py
  inspirehep/modules/workflows/workflows/article.py
  tests/unit/workflows/test_workflows_tasks_actions.py
  tests/unit/workflows/test_workflows_tasks_refextract.py
  tests/unit/workflows/test_workflows_tasks_submission.py
Labels: Review: WIP, Status: Ready for review

#3188 error_pages: adjust feedback email address
  inspirehep/modules/theme/templates/inspirehep_theme/errors/500.html
Labels: Review: In Review

#3189 workflows: show useful message on validation error
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/workflows/article.py
  tests/integration/workflows/test_arxiv_workflow.py
Labels: Review: Ready for Review

#3186 rt: fix rt ticket creation for harvests
  inspirehep/modules/literaturesuggest/tasks.py
  inspirehep/modules/workflows/tasks/submission.py
  tests/integration/workflows/conftest.py
Labels: Review: WIP, Status: Ready for integration

#3190 workflows: don't auto-reject auto-approved workflows
  inspirehep/modules/workflows/tasks/actions.py
  tests/unit/workflows/test_workflows_tasks_actions.py
Labels: Review: WIP

#3192 hal: also send the subtitle
  inspirehep/modules/hal/core/tei.py
  inspirehep/modules/hal/templates/hal/art.xml
  inspirehep/modules/hal/templates/hal/comm.xml
  inspirehep/modules/hal/templates/hal/preprint.xml
Labels: Review: WIP

#3191 git: ignore items created by scrapy runs
  .gitignore
Labels: Review: WIP

#3207 authors.tasks.update_ticket_context: require recid
  inspirehep/modules/authors/tasks.py
  tests/unit/authors/test_authors_tasks.py
Labels: Review: Ready for Review

#3199 workflows: add hp card for all publisher harvests
  inspirehep/modules/workflows/templates/inspire_workflows/index.html
Labels: Review: WIP

#3203 setup: unpin SQLAlchemy-Utils
  setup.py
Labels: Review: Ready for Review

#3198 authors: validate at the beginning of the workflow
  inspirehep/modules/authors/tasks.py
  inspirehep/modules/workflows/tasks/actions.py
  inspirehep/modules/workflows/workflows/article.py
  inspirehep/modules/workflows/workflows/author.py
  tests/integration/workflows/conftest.py
  tests/integration/workflows/test_authors_workflow.py
  tests/unit/workflows/test_workflows_tasks_actions.py
Labels: Review: Ready for Review

#3201 search: remove annoying exception
  inspirehep/modules/search/api.py
Labels: Review: Ready for Review

#3205 refextract: correctly generate journal KB
  inspirehep/modules/refextract/utils.py
  tests/unit/refextract/test_refextract_utils.py
Labels: Review: In Review

#3211 workflows: fix of rt duplication
  inspirehep/modules/workflows/workflows/article.py
Labels: Review: WIP

#3210 orcid: fix ``MemberAPI`` search
  inspirehep/modules/forms/validation_utils.py
  tests/unit/forms/test_forms_validation_utils.py
Labels: Review: WIP

#3209 records.receivers: re-add receivers registration
  inspirehep/modules/records/ext.py
  setup.py
Labels: Review: WIP

#3202 setup: temporary replace ``invenio-indexer``
  requirements.txt
  setup.py
Labels: Review: Ready for Integration

#3206 workflows: add bottom margin to resolve errors btn
  inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
Labels: Review: Ready for Integration

#3214 orcid: bugfix: last cached record is always pushed
  inspirehep/modules/orcid/api.py
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/conftest.py
  tests/integration/orcid/test_orcid_push.py
Labels: Review: Ready for Review

#3216 docker: clean up pidfile when starting scrapyd
  docker-compose.yml
Labels: Review: Ready for Review

#3150 theme: add style to the possible matches UI
  inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
  inspirehep/modules/workflows/search.py
Labels: Review: In Review, project/UI

#3219 setup: fix ``invenio-indexer`` requirement
  requirements.txt
Labels: Review: WIP

#3221 orcid: don't rely on self_recid in record in OrcidConverter
  inspirehep/modules/orcid/converter.py
Labels: Review: WIP

#3217 orcid: bugfix: don't confuse client_id with ORCID
  inspirehep/modules/orcid/tasks.py
  tests/integration/orcid/test_orcid_import_legacy_tokens.py
Labels: Review: WIP
